services:
  - type: web
    name: camplots-backend
    runtime: node
    buildCommand: |
      npm ci
      npm run build --workspace=backend
    startCommand: npm start --workspace=backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
