services:
  - type: web
    name: camplots-backend
    runtime: node
    rootDir: packages/backend
    buildCommand: |
      cd ../../
      npm ci
      cd packages/backend
      npm ci
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
